ident fix

diff --git a/.gitea/workflows/run_act.yaml b/.gitea/workflows/run_act.yaml
--- a/.gitea/workflows/run_act.yaml
+++ b/.gitea/workflows/run_act.yaml
@@ -58,9 +58,9 @@ jobs:
 
       - name: Indicate Failure
         run: | 
-        echo ${{ failure() }}
-        echo "Failure detected"
-        exit ${{ failure() }}
+          echo ${{ failure() }}
+          echo "Failure detected"
+          exit ${{ failure() }}
       
       - name: Indicate Failure 2
         if:  ${{ failure() }}
